/* 
   CANONICAL SETTINGS.JS
   Generated by Samuel Ezekiel 
   DO NOT MODIFY VALUES MANUALLY - MANAGED BY DEPLOYMENT PLATFORM
*/

const settings = {
  // --- IDENTITY ---
  botName: "SAMKIEL BOT", // String: Display name in greetings
  prefix: ".", // String: Command prefix (e.g. ".", "!", or "off")
  botNumber: "", // String: Bot's number (e.g., "2348087357158"). Empty string allows internal resolution.
  ownerNumber: "2348087357158", // String: PURE NUMBER ONLY (No + or spaces). Critical for access control.
  ownerName: "SAMKIEL", // String: Owner display name

  // --- CREDITS ---
  author: "𝕊𝔸𝕄𝕂𝕀𝔼𝕃 𝔹𝕆𝕋", // String: Sticker pack author
  packname: "𝕊𝔸𝕄𝕂𝕀𝔼𝕃 𝔹𝕆𝕋", // String: Sticker pack name (mapped from featureToggles.PACKNAME)
  developer: "ѕαмкιєℓ.∂єν", // String: Footer text
  portfolio: "https://samkiel.dev", // String: URL
  website: "https://samkielbot.app", // String: URL
  description: "Whatsapp Bot", // String: Metadata
  version: "2.2.0", // String: Version

  // --- FEATURE TOGGLES ---
  featureToggles: {
    // ⚠️ CRITICAL: LOGIC REQUIRES STRINGS FOR THESE TWO
    AUTO_STATUS_VIEW: "on", // "on" | "off" (Boolean FALSE will force this ON)
    STATUS_VIEW_MSG: "off", // "on" | "off" (Boolean TRUE will force this OFF)

    // Standard Booleans
    ENABLE_STATUS_REACTION: true, // Boolean
    ANTI_DELETE: true, // Boolean
    SEND_READ: false, // Boolean (Blue ticks)
    ALWAYS_ONLINE: true, // Boolean
    REJECT_CALL: false, // Boolean
    PERSONAL_MESSAGE: false, // Boolean (If true, bot ignores groups)
    DISABLE_START_MESSAGE: false, // Boolean

    AUTO_REACTION: false, // Boolean

    // Configuration Strings
    STATUS_VIEW_EMOJI: "👀", // String
    ANTI_DELETE_TYPE: "group", // "group" | "dm"
    COMMAND_MODE: "private", // "public" | "private"

    // Aliased from root for legacy support
    PACKNAME: "𝕊𝔸𝕄𝕂𝕀𝔼𝕃 𝔹𝕆𝕋",
  },

  // --- INTERNAL ---
  giphyApiKey: "qnl7ssQChTdPjsKta2Ax2LMaGXz303tq",
  updateZipUrl:
    "https://github.com/samkiell/SAMKIEL-AI/archive/refs/heads/main.zip",
};

module.exports = settings;
