const fetch = require("node-fetch");

async function lyricsCommand(sock, chatId, songTitle, message) {
  if (!songTitle) {
    await sock.sendMessage(
      chatId,
      {
        text: "🔍 Please enter the song name to get the lyrics! Usage: *lyrics <song name>*",
        ...global.channelInfo,
      },
      { quoted: message }
    );
    return;
  }

  try {
    // List of providers to try for lyrics
    const providers = [
      {
        url: `https://lrclib.net/api/search?q=${encodeURIComponent(songTitle)}`,
        type: "lrclib",
      },
      {
        url: `https://api.lyrics.ovh/v1/${encodeURIComponent(
          songTitle.split(" ").slice(0, 2).join(" ")
        )}/${encodeURIComponent(songTitle.split(" ").slice(2).join(" "))}`,
        type: "lyricsovh",
      },
      {
        url: `https://api.popcat.xyz/lyrics?song=${encodeURIComponent(
          songTitle
        )}`,
        type: "popcat",
      },
    ];

    let lyrics = null;

    for (const provider of providers) {
      try {
        const res = await fetch(provider.url);
        if (!res.ok) continue;

        const data = await res.json();
        let content = null;

        if (provider.type === "lrclib") {
          if (Array.isArray(data) && data.length > 0) {
            content = data[0].plainLyrics || data[0].lyrics;
          }
        } else if (provider.type === "lyricsovh") {
          content = data.lyrics;
        } else if (provider.type === "popcat") {
          content = data.lyrics;
        }

        if (content && content.length > 50) {
          lyrics = content;
          break;
        }
      } catch (e) {
        console.warn(`Lyrics provider failed: ${provider.url}`, e.message);
        continue;
      }
    }

    if (!lyrics) {
      await sock.sendMessage(
        chatId,
        {
          text: `❌ Sorry, I couldn't find any lyrics for "${songTitle}".\nTry asking the AI directly: *gpt lyrics for ${songTitle}*`,
          ...global.channelInfo,
        },
        { quoted: message }
      );
      return;
    }

    const maxChars = 4096;
    const output =
      lyrics.length > maxChars ? lyrics.slice(0, maxChars - 3) + "..." : lyrics;

    await sock.sendMessage(
      chatId,
      {
        text: `🎤 *Lyrics for ${songTitle}*\n(Generated by AI)\n\n${output}`,
        ...global.channelInfo,
      },
      { quoted: message }
    );
  } catch (error) {
    console.error("Error in lyrics command:", error);
    await sock.sendMessage(
      chatId,
      {
        text: `❌ Failed to fetch lyrics. \nTip: You can ask the AI for lyrics using:\n*gpt lyrics for ${songTitle}*`,
        ...global.channelInfo,
      },
      { quoted: message }
    );
  }
}

module.exports = { lyricsCommand };
