const fetch = require("node-fetch");

async function lyricsCommand(sock, chatId, songTitle, message) {
  if (!songTitle) {
    await sock.sendMessage(
      chatId,
      {
        text: "🔍 Please enter the song name to get the lyrics! Usage: *lyrics <song name>*",
      },
      { quoted: message }
    );
    return;
  }

  try {
    // Use AI to generate/fetch lyrics as it is more reliable than scraping APIs
    // Primary: Widipe OpenAI
    let apiUrl = `https://widipe.com/openai?text=${encodeURIComponent(
      `lyrics for ${songTitle} by song name/artist`
    )}`;
    let res = await fetch(apiUrl);
    let data = await res.json();

    // Validation: Check if response looks like lyrics (length > 50, contains newlines)
    let lyrics = data.result || data.message || data.answer;

    if (!lyrics || lyrics.length < 50) {
      // Fallback: BK9 GPT4
      apiUrl = `https://bk9.fun/ai/gpt4?q=${encodeURIComponent(
        `lyrics for ${songTitle}`
      )}`;
      res = await fetch(apiUrl);
      data = await res.json();
      lyrics = data.BK9 || data.result || data.message;
    }

    if (!lyrics) {
      await sock.sendMessage(
        chatId,
        {
          text: `❌ Sorry, I couldn't find any lyrics for "${songTitle}".\nTry asking the AI directly: *gpt lyrics for ${songTitle}*`,
        },
        { quoted: message }
      );
      return;
    }

    const maxChars = 4096;
    const output =
      lyrics.length > maxChars ? lyrics.slice(0, maxChars - 3) + "..." : lyrics;

    await sock.sendMessage(
      chatId,
      {
        text: `🎤 *Lyrics for ${songTitle}*\n(Generated by AI)\n\n${output}`,
      },
      { quoted: message }
    );
  } catch (error) {
    console.error("Error in lyrics command:", error);
    await sock.sendMessage(
      chatId,
      {
        text: `❌ Failed to fetch lyrics. \nTip: You can ask the AI for lyrics using:\n*gpt lyrics for ${songTitle}*`,
      },
      { quoted: message }
    );
  }
}

module.exports = { lyricsCommand };
