const fetch = require("node-fetch");

async function lyricsCommand(sock, chatId, songTitle, message) {
  if (!songTitle) {
    await sock.sendMessage(
      chatId,
      {
        text: "🔍 Please enter the song name to get the lyrics! Usage: *lyrics <song name>*",
        ...global.channelInfo,
      },
      { quoted: message }
    );
    return;
  }

  try {
    // List of AI providers to try for lyrics
    const providers = [
      `https://bk9.fun/ai/gpt4?q=${encodeURIComponent(
        `lyrics for ${songTitle}`
      )}`,
      `https://widipe.com/openai?text=${encodeURIComponent(
        `lyrics for ${songTitle} by song name/artist`
      )}`,
      `https://api.dark-yasiya-api.vercel.app/chat/gpt?query=${encodeURIComponent(
        `lyrics for ${songTitle}`
      )}`,
      `https://api.popcat.xyz/chatbot?owner=Samkiel&botname=SamkielAI&msg=${encodeURIComponent(
        `lyrics for ${songTitle}`
      )}`,
    ];

    let lyrics = null;

    for (const apiUrl of providers) {
      try {
        const res = await fetch(apiUrl);
        if (!res.ok) {
          // Try next if status not 200
          console.warn(
            `Lyrics provider ${apiUrl} returned non-OK status: ${res.status}`
          );
          continue;
        }

        const data = await res.json();
        // Check potential response fields
        const content =
          data.BK9 || data.result || data.message || data.answer || data.reply;

        // Validate content looks like lyrics
        if (content && typeof content === "string" && content.length > 50) {
          lyrics = content;
          break; // Found valid lyrics, stop looping
        }
      } catch (e) {
        console.warn(`Lyrics provider failed: ${apiUrl}`, e.message);
        continue; // Try next provider on error
      }
    }

    if (!lyrics) {
      await sock.sendMessage(
        chatId,
        {
          text: `❌ Sorry, I couldn't find any lyrics for "${songTitle}".\nTry asking the AI directly: *gpt lyrics for ${songTitle}*`,
          ...global.channelInfo,
        },
        { quoted: message }
      );
      return;
    }

    const maxChars = 4096;
    const output =
      lyrics.length > maxChars ? lyrics.slice(0, maxChars - 3) + "..." : lyrics;

    await sock.sendMessage(
      chatId,
      {
        text: `🎤 *Lyrics for ${songTitle}*\n(Generated by AI)\n\n${output}`,
        ...global.channelInfo,
      },
      { quoted: message }
    );
  } catch (error) {
    console.error("Error in lyrics command:", error);
    await sock.sendMessage(
      chatId,
      {
        text: `❌ Failed to fetch lyrics. \nTip: You can ask the AI for lyrics using:\n*gpt lyrics for ${songTitle}*`,
        ...global.channelInfo,
      },
      { quoted: message }
    );
  }
}

module.exports = { lyricsCommand };
